//go:build !darwin && !linux && !windows
// +build !darwin,!linux,!windows

// Copyright 2012 The Chromium Authors
// Copyright 2026 Mozilla
// Copyright 2026 LumiFloat
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
package text

var (
	FONT_FANTASY_FONT_FAMILY = []string{}
	FONT_EMOJI_FONT_FAMILY   = []string{}
	FONT_MATH_FONT_FAMILY    = []string{}

	FONT_SERIF_FONT_FAMILY_ARAB      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ARAB = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ARAB  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ARAB    = []string{}

	FONT_SERIF_FONT_FAMILY_ARMN      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ARMN = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ARMN  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ARMN    = []string{}

	FONT_SERIF_FONT_FAMILY_BENG      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_BENG = []string{}
	FONT_MONOSPACE_FONT_FAMILY_BENG  = []string{}
	FONT_CURSIVE_FONT_FAMILY_BENG    = []string{}

	FONT_SERIF_FONT_FAMILY_CANS      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_CANS = []string{}
	FONT_MONOSPACE_FONT_FAMILY_CANS  = []string{}
	FONT_CURSIVE_FONT_FAMILY_CANS    = []string{}

	FONT_SERIF_FONT_FAMILY_CYRL      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_CYRL = []string{}
	FONT_MONOSPACE_FONT_FAMILY_CYRL  = []string{}
	FONT_CURSIVE_FONT_FAMILY_CYRL    = []string{}

	FONT_SERIF_FONT_FAMILY_DEVA      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_DEVA = []string{}
	FONT_MONOSPACE_FONT_FAMILY_DEVA  = []string{}
	FONT_CURSIVE_FONT_FAMILY_DEVA    = []string{}

	FONT_SERIF_FONT_FAMILY_ETHI      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ETHI = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ETHI  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ETHI    = []string{}

	FONT_SERIF_FONT_FAMILY_GEOR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_GEOR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_GEOR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_GEOR    = []string{}

	FONT_SERIF_FONT_FAMILY_GREK      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_GREK = []string{}
	FONT_MONOSPACE_FONT_FAMILY_GREK  = []string{}
	FONT_CURSIVE_FONT_FAMILY_GREK    = []string{}

	FONT_SERIF_FONT_FAMILY_GUJR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_GUJR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_GUJR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_GUJR    = []string{}

	FONT_SERIF_FONT_FAMILY_GURU      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_GURU = []string{}
	FONT_MONOSPACE_FONT_FAMILY_GURU  = []string{}
	FONT_CURSIVE_FONT_FAMILY_GURU    = []string{}

	FONT_SERIF_FONT_FAMILY_HANS      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_HANS = []string{}
	FONT_MONOSPACE_FONT_FAMILY_HANS  = []string{}
	FONT_CURSIVE_FONT_FAMILY_HANS    = []string{}

	FONT_SERIF_FONT_FAMILY_HANT      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_HANT = []string{}
	FONT_MONOSPACE_FONT_FAMILY_HANT  = []string{}
	FONT_CURSIVE_FONT_FAMILY_HANT    = []string{}

	FONT_SERIF_FONT_FAMILY_HEBR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_HEBR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_HEBR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_HEBR    = []string{}

	FONT_SERIF_FONT_FAMILY_JPAN      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_JPAN = []string{}
	FONT_MONOSPACE_FONT_FAMILY_JPAN  = []string{}
	FONT_CURSIVE_FONT_FAMILY_JPAN    = []string{}

	FONT_SERIF_FONT_FAMILY_KHMR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_KHMR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_KHMR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_KHMR    = []string{}

	FONT_SERIF_FONT_FAMILY_KNDA      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_KNDA = []string{}
	FONT_MONOSPACE_FONT_FAMILY_KNDA  = []string{}
	FONT_CURSIVE_FONT_FAMILY_KNDA    = []string{}

	FONT_SERIF_FONT_FAMILY_KORE      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_KORE = []string{}
	FONT_MONOSPACE_FONT_FAMILY_KORE  = []string{}
	FONT_CURSIVE_FONT_FAMILY_KORE    = []string{}

	FONT_SERIF_FONT_FAMILY_LATN      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_LATN = []string{}
	FONT_MONOSPACE_FONT_FAMILY_LATN  = []string{}
	FONT_CURSIVE_FONT_FAMILY_LATN    = []string{}

	FONT_SERIF_FONT_FAMILY_MLYM      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_MLYM = []string{}
	FONT_MONOSPACE_FONT_FAMILY_MLYM  = []string{}
	FONT_CURSIVE_FONT_FAMILY_MLYM    = []string{}

	FONT_SERIF_FONT_FAMILY_ORYA      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ORYA = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ORYA  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ORYA    = []string{}

	FONT_SERIF_FONT_FAMILY_SINH      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_SINH = []string{}
	FONT_MONOSPACE_FONT_FAMILY_SINH  = []string{}
	FONT_CURSIVE_FONT_FAMILY_SINH    = []string{}

	FONT_SERIF_FONT_FAMILY_TAML      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_TAML = []string{}
	FONT_MONOSPACE_FONT_FAMILY_TAML  = []string{}
	FONT_CURSIVE_FONT_FAMILY_TAML    = []string{}

	FONT_SERIF_FONT_FAMILY_TELU      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_TELU = []string{}
	FONT_MONOSPACE_FONT_FAMILY_TELU  = []string{}
	FONT_CURSIVE_FONT_FAMILY_TELU    = []string{}

	FONT_SERIF_FONT_FAMILY_THAI      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_THAI = []string{}
	FONT_MONOSPACE_FONT_FAMILY_THAI  = []string{}
	FONT_CURSIVE_FONT_FAMILY_THAI    = []string{}

	FONT_SERIF_FONT_FAMILY_TIBT      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_TIBT = []string{}
	FONT_MONOSPACE_FONT_FAMILY_TIBT  = []string{}
	FONT_CURSIVE_FONT_FAMILY_TIBT    = []string{}
)
