// Copyright 2012 The Chromium Authors
// Copyright 2026 Mozilla
// Copyright 2026 LumiFloat
//
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
package text

var (
	FONT_EMOJI_FONT_FAMILY = []string{}

	FONT_SERIF_FONT_FAMILY_AR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_AR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_AR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_AR    = []string{}

	FONT_SERIF_FONT_FAMILY_ARMN      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ARMN = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ARMN  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ARMN    = []string{}

	FONT_SERIF_FONT_FAMILY_BENG      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_BENG = []string{}
	FONT_MONOSPACE_FONT_FAMILY_BENG  = []string{}
	FONT_CURSIVE_FONT_FAMILY_BENG    = []string{}

	FONT_SERIF_FONT_FAMILY_CANS      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_CANS = []string{}
	FONT_MONOSPACE_FONT_FAMILY_CANS  = []string{}
	FONT_CURSIVE_FONT_FAMILY_CANS    = []string{}

	FONT_SERIF_FONT_FAMILY_CYRILLIC      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_CYRILLIC = []string{}
	FONT_MONOSPACE_FONT_FAMILY_CYRILLIC  = []string{}
	FONT_CURSIVE_FONT_FAMILY_CYRILLIC    = []string{}

	FONT_SERIF_FONT_FAMILY_DEVANAGARI      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_DEVANAGARI = []string{}
	FONT_MONOSPACE_FONT_FAMILY_DEVANAGARI  = []string{}
	FONT_CURSIVE_FONT_FAMILY_DEVANAGARI    = []string{}

	FONT_SERIF_FONT_FAMILY_ETHI      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ETHI = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ETHI  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ETHI    = []string{}

	FONT_SERIF_FONT_FAMILY_EL      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_EL = []string{}
	FONT_MONOSPACE_FONT_FAMILY_EL  = []string{}
	FONT_CURSIVE_FONT_FAMILY_EL    = []string{}

	FONT_SERIF_FONT_FAMILY_GEOR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_GEOR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_GEOR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_GEOR    = []string{}

	FONT_SERIF_FONT_FAMILY_GUJR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_GUJR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_GUJR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_GUJR    = []string{}

	FONT_SERIF_FONT_FAMILY_GURU      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_GURU = []string{}
	FONT_MONOSPACE_FONT_FAMILY_GURU  = []string{}
	FONT_CURSIVE_FONT_FAMILY_GURU    = []string{}

	FONT_SERIF_FONT_FAMILY_HE      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_HE = []string{}
	FONT_MONOSPACE_FONT_FAMILY_HE  = []string{}
	FONT_CURSIVE_FONT_FAMILY_HE    = []string{}

	FONT_SERIF_FONT_FAMILY_JA      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_JA = []string{}
	FONT_MONOSPACE_FONT_FAMILY_JA  = []string{}
	FONT_CURSIVE_FONT_FAMILY_JA    = []string{}

	FONT_SERIF_FONT_FAMILY_KHMR      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_KHMR = []string{}
	FONT_MONOSPACE_FONT_FAMILY_KHMR  = []string{}
	FONT_CURSIVE_FONT_FAMILY_KHMR    = []string{}

	FONT_SERIF_FONT_FAMILY_KNDA      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_KNDA = []string{}
	FONT_MONOSPACE_FONT_FAMILY_KNDA  = []string{}
	FONT_CURSIVE_FONT_FAMILY_KNDA    = []string{}

	FONT_SERIF_FONT_FAMILY_KO      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_KO = []string{}
	FONT_MONOSPACE_FONT_FAMILY_KO  = []string{}
	FONT_CURSIVE_FONT_FAMILY_KO    = []string{}

	FONT_SERIF_FONT_FAMILY_MLYM      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_MLYM = []string{}
	FONT_MONOSPACE_FONT_FAMILY_MLYM  = []string{}
	FONT_CURSIVE_FONT_FAMILY_MLYM    = []string{}

	FONT_SERIF_FONT_FAMILY_ORYA      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ORYA = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ORYA  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ORYA    = []string{}

	FONT_SERIF_FONT_FAMILY_SINH      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_SINH = []string{}
	FONT_MONOSPACE_FONT_FAMILY_SINH  = []string{}
	FONT_CURSIVE_FONT_FAMILY_SINH    = []string{}

	FONT_SERIF_FONT_FAMILY_TAMIL      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_TAMIL = []string{}
	FONT_MONOSPACE_FONT_FAMILY_TAMIL  = []string{}
	FONT_CURSIVE_FONT_FAMILY_TAMIL    = []string{}

	FONT_SERIF_FONT_FAMILY_TELU      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_TELU = []string{}
	FONT_MONOSPACE_FONT_FAMILY_TELU  = []string{}
	FONT_CURSIVE_FONT_FAMILY_TELU    = []string{}

	FONT_SERIF_FONT_FAMILY_TH      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_TH = []string{}
	FONT_MONOSPACE_FONT_FAMILY_TH  = []string{}
	FONT_CURSIVE_FONT_FAMILY_TH    = []string{}

	FONT_SERIF_FONT_FAMILY_TIBT      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_TIBT = []string{}
	FONT_MONOSPACE_FONT_FAMILY_TIBT  = []string{}
	FONT_CURSIVE_FONT_FAMILY_TIBT    = []string{}

	FONT_SERIF_FONT_FAMILY_UNICODE      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_UNICODE = []string{}
	FONT_MONOSPACE_FONT_FAMILY_UNICODE  = []string{}
	FONT_CURSIVE_FONT_FAMILY_UNICODE    = []string{}

	FONT_SERIF_FONT_FAMILY_WESTERN      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_WESTERN = []string{}
	FONT_MONOSPACE_FONT_FAMILY_WESTERN  = []string{}
	FONT_CURSIVE_FONT_FAMILY_WESTERN    = []string{}

	FONT_SERIF_FONT_FAMILY_ZH_CN      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ZH_CN = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ZH_CN  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ZH_CN    = []string{}

	FONT_SERIF_FONT_FAMILY_ZH_HK      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ZH_HK = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ZH_HK  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ZH_HK    = []string{}

	FONT_SERIF_FONT_FAMILY_ZH_TW      = []string{}
	FONT_SANS_SERIF_FONT_FAMILY_ZH_TW = []string{}
	FONT_MONOSPACE_FONT_FAMILY_ZH_TW  = []string{}
	FONT_CURSIVE_FONT_FAMILY_ZH_TW    = []string{}
)
